# Generated by Django 6.0.6 on 2026-07-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX")], max_length=10
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(help_text="File size in bytes."),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "skill_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "semantic_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "section_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "achievement_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "readability_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "semantic_similarity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("resume_skills", models.JSONField(blank=True, default=list)),
                ("job_skills", models.JSONField(blank=True, default=list)),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("section_results", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                (
                    "analysis_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Processing time in milliseconds.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="analyzer.jobdescription",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="analyzer.resume",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resume analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
